export { default as Document } from './document';
export { default as Page } from './page';
export { default as PageHeader } from './page_header';
export { default as PageContent } from './page_content';
export { default as PageBottom } from './page_bottom';
export { default as Checkbox } from './checkbox';
export { default as AccentCapsule } from './accent_capsule';
export { accentCapsuleSurface } from './accent_capsule/surface';
export { PDF, PDF_PADDING } from './pdf_theme';
export { PdfHeader, PdfFooter } from './pdf_chrome';
export { fechaCorta } from './pdf_chrome/fecha';
